#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DragSortList.Resource", IsApplication=true)]

namespace DragSortList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int click_remove_id = 2130771984;
			
			// aapt resource value: 0x7f010000
			public const int collapsed_height = 2130771968;
			
			// aapt resource value: 0x7f01000a
			public const int drag_enabled = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int drag_handle_id = 2130771982;
			
			// aapt resource value: 0x7f010001
			public const int drag_scroll_start = 2130771969;
			
			// aapt resource value: 0x7f01000d
			public const int drag_start_mode = 2130771981;
			
			// aapt resource value: 0x7f010009
			public const int drop_animation_duration = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public const int fling_handle_id = 2130771983;
			
			// aapt resource value: 0x7f010006
			public const int float_alpha = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int float_background_color = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int max_drag_scroll_speed = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int remove_animation_duration = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int remove_enabled = 2130771980;
			
			// aapt resource value: 0x7f010004
			public const int remove_mode = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int slide_shuffle_speed = 2130771975;
			
			// aapt resource value: 0x7f01000b
			public const int sort_enabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int track_drag_sort = 2130771973;
			
			// aapt resource value: 0x7f010011
			public const int use_default_controller = 2130771985;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int grabber = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int clickRemove = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int drag_handle = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int flingRemove = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int layoutClick = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int name = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int onDown = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int onLongPress = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int onMove = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int simpleDragListview = 2130968582;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_drag_sort_list_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int simple_drag_list_item = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] DragSortListView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 16
			public const int DragSortListView_click_remove_id = 16;
			
			// aapt resource value: 0
			public const int DragSortListView_collapsed_height = 0;
			
			// aapt resource value: 10
			public const int DragSortListView_drag_enabled = 10;
			
			// aapt resource value: 14
			public const int DragSortListView_drag_handle_id = 14;
			
			// aapt resource value: 1
			public const int DragSortListView_drag_scroll_start = 1;
			
			// aapt resource value: 13
			public const int DragSortListView_drag_start_mode = 13;
			
			// aapt resource value: 9
			public const int DragSortListView_drop_animation_duration = 9;
			
			// aapt resource value: 15
			public const int DragSortListView_fling_handle_id = 15;
			
			// aapt resource value: 6
			public const int DragSortListView_float_alpha = 6;
			
			// aapt resource value: 3
			public const int DragSortListView_float_background_color = 3;
			
			// aapt resource value: 2
			public const int DragSortListView_max_drag_scroll_speed = 2;
			
			// aapt resource value: 8
			public const int DragSortListView_remove_animation_duration = 8;
			
			// aapt resource value: 12
			public const int DragSortListView_remove_enabled = 12;
			
			// aapt resource value: 4
			public const int DragSortListView_remove_mode = 4;
			
			// aapt resource value: 7
			public const int DragSortListView_slide_shuffle_speed = 7;
			
			// aapt resource value: 11
			public const int DragSortListView_sort_enabled = 11;
			
			// aapt resource value: 5
			public const int DragSortListView_track_drag_sort = 5;
			
			// aapt resource value: 17
			public const int DragSortListView_use_default_controller = 17;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
